### PR TITLE
Fix IRQ_SAFE mode and make it the default

### LINKED ISSUE #5: IRQ_SAFE in pimp_mixer_arm.S is borked
Compare:

https://github.com/kusma/pimpmobile/blob/master/src/pimp_mixer_arm.S#L61-L63

https://github.com/kusma/pimpmobile/blob/master/src/pimp_mixer_arm.S#L303

Also, `IRQ_SAFE` should maybe be made the default.

I might write a fix for this Soon™ (probably right after FOSDEM)

### PR DESCRIPTION
**Pull request by PoroCYon**
Fixes #5

### CODE REVIEW

**Comment by PoroCYon** [comment]
```
src/pimp_mixer.c:7:10: fatal error: gba.h: No such file or directory
    7 | #include <gba.h>
      |          ^~~~~~~
```

I think the CI is borked?

**Comment by kusma** [comment]
Doesn't seem like it, I just gave it a go here, and it passed: https://travis-ci.org/kusma/pimpmobile/builds/638811708

File: src/pimp_base.h [hunk 1]
```diff
@@ -16,6 +17,7 @@ typedef unsigned int       u32;
 #endif
 typedef   signed long long s64;
 typedef unsigned long long u64;
+#endif
```
Comment (kusma) [inline src/pimp_base.h]: Why do you need to do this?

File: src/pimp_mixer.c [hunk 2]
```diff
@@ -3,6 +3,10 @@
  * For conditions of distribution and use, see copyright notice in LICENSE.TXT
  */
 
+#ifdef TARGET_GBA
+#include <gba.h>
+#endif
```
Comment (kusma) [inline src/pimp_mixer.c]: It's unclear why you want to change this...

File: src/pimp_mixer.c [hunk 3]
```diff
@@ -51,21 +55,22 @@ PURE int pimp_calc_loop_event(int event_cursor, int event_delta, const int max_s
...
+//#else
+//			"swi 0x6 << 16     \n"
+//#endif
+//			"mov %[result], r0 \n"
+//			: [result] "=r" (result) /* output */
+//			: /* inputs */
+//				[number] "r" (number),
+//				[denom] "r" (denom)
+//			: "r0", "r1", "r2", "r3" /* clobbers */
+//		);
```
Comment (kusma) [inline src/pimp_mixer.c]: So, I've tried not to use libgba in the player itself, only in the example. This is so people who doesn't use libgba can also use pimpmobile.

File: src/pimp_mixer_arm.S [hunk 4]
```diff
@@ -20,15 +20,14 @@
 @irq-safe:   1121327
 @irq-unsafe: 1105083
 
-// #define IRQ_SAFE
+#define IRQ_SAFE /* on by default */
```
Comment (kusma) [inline src/pimp_mixer_arm.S]: I think it would be better to turn this into a define in the build-system than defining it in this source. And I think it would be good to make this a separate commit from fixing the logic.

File: src/pimp_mixer_arm.S [hunk 5]
```diff
@@ -20,15 +20,14 @@
...
 #define USE_BRESENHAM_MIXER
 // #define NO_MIXING
 // #define NO_CLIPPING
 
+#ifndef IRQ_SAFE
 .stack_store:
 .word 0
-
-#ifndef IRQ_SAFE
```
Comment (kusma) [inline src/pimp_mixer_arm.S:31]: So, this hunk makes sure that stack_store doesn't take up space when it's not used? Nice, but could perhaps be a separate commit for reviewability...

File: src/pimp_mixer_arm.S [hunk 6]
```diff
@@ -214,13 +213,14 @@ pimp_mixer_mix_samples:
 	ldr r4, =0x4000208 @ load address of REG_IME
 	ldr r5, .ime_store @ stash for later
```
Comment (kusma) [inline src/pimp_mixer_arm.S:211]: I guess this comment should have said "restore value"

File: src/pimp_mixer_arm.S [hunk 7]
```diff
@@ -298,9 +298,10 @@ pimp_mixer_mix_samples:
...
```
Comment (kusma) [inline src/pimp_mixer_arm.S:296]: Similarly, I think this comment should have read "restore value"

File: src/pimp_mixer_arm.S [hunk 8]
```diff
@@ -298,9 +298,10 @@ pimp_mixer_mix_samples:
...
 	str r5, [r4]       @ write value to REG_IME
-#endif
 	
 	ldr sp, .stack_store       @ restore stack pointer
+#endif
+
```
Comment (kusma) [inline src/pimp_mixer_arm.S:301]: This looks good!

File: src/pimp_mixer_arm.S [hunk 9]
```diff
@@ -214,13 +213,14 @@ pimp_mixer_mix_samples:
...
 	str r5, [r4]       @ write value to REG_IME
+
+	ldr sp, .stack_store    @ restore stack pointer
 #endif
 	
 .ret:
 	@ clean return
 	mov r0, SAMPLE_CURSOR
 	
-	ldr sp, .stack_store    @ restore stack pointer
```
Comment (kusma) [inline src/pimp_mixer_arm.S:223]: This one is technically correct, and I think we should just do it. But there's one thing that bothers me: It's asymmetrical. Before, we had one store at entry and one restore at exit. Now we omit the restore when we terminate after the "fixup"-process (by branching to .ret). But it's not *incorrect*, because we haven't clobbered the stack-pointer yet.

**Review by kusma — CHANGES_REQUESTED** [review]
So, I think the reason the CI fails is that the build-system isn't set up to allow using libgba for the main library, just for the examples. I guess you don't use the build-system? If you do, I'm curious how this compiles for you...

File: src/pimp_mixer_arm.S (hunk 6 above)
Comment (kusma) [reply src/pimp_mixer_arm.S:211]: This was just a note to myself, though. I'm not asking you to fix the comment ;)

File: src/pimp_mixer_arm.S (hunk 7 above)
Comment (kusma) [reply src/pimp_mixer_arm.S:296]: This was just a note to myself, though. I'm not asking you to fix the comment ;)

File: src/pimp_base.h (hunk 1 above)
Comment (PoroCYon) [reply src/pimp_base.h]: The libgba headers define these types already, and guard it with that macro. All this does is making sure that these don't get redefined if the order of the included headers is 'bad'.

File: src/pimp_mixer.c (hunk 2 above)
Comment (PoroCYon) [reply src/pimp_mixer.c]: I was compiling it with LTO, which made the `__thumb__` macro be mistakenly (not) defined because the actual code generated happened in a later step.

I do understand the argument for not wanting to rely on libgba, but I'm not sure how to remove this dependency *and* enable LTO (except for adding this `Div` function separately somewhere). I simply took this because it's the code I used for [Uitslaganticipatieangst 2](https://www.pouet.net/prod.php?which=84533).

File: src/pimp_mixer.c (hunk 3 above)
Comment (PoroCYon) [reply src/pimp_mixer.c]: See [above comment](https://www.pouet.net/prod.php?which=84533)

**Comment by PoroCYon** [comment]
I'm calling the pimpmobile Makefile from another Makefile (for the main project) which already adds the libgba include dirs to `CFLAGS` etc., so that's probably what's contaminating the environment...

File: src/pimp_mixer_arm.S (hunk 4 above)
Comment (PoroCYon) [reply src/pimp_mixer_arm.S]: Right. But should this be added to `pimp_config.h`, or should the macros there also be configurable from the build system? (Or am I using it incorrectly? I'm just calling the Makefile, is there other stuff I should do before that?)

File: src/pimp_mixer_arm.S (hunk 5 above)
Comment (PoroCYon) [reply src/pimp_mixer_arm.S:31]: Fair enough.

(EDIT: waiting for replies on the other things so I can do everything at once.)

File: src/pimp_mixer_arm.S (hunk 9 above)
Comment (PoroCYon) [reply src/pimp_mixer_arm.S:223]: By "I think we should just do it" do you mean removing this line, or restoring sp (i.e. keeping the line)? Or should I insert an `ldreq ...` before line 135? Or move the `sp`-saving code to line 136 or sth?

File: src/pimp_mixer.c (hunk 2 above)
Comment (kusma) [reply src/pimp_mixer.c]: Right. We don't use LTO for pipmobile, so this sounds like user-error ;)

I think you should carry this patch in your own fork for now. I don't think compiling pimpmobile with LTO is a worthwhile goal right now.

File: src/pimp_base.h (hunk 1 above)
Comment (kusma) [reply src/pimp_base.h]: `pimp_base.h` is in src, so it's not meant to be included by 3rd party code; it's not part of the API. So I don't think there's any risk of this happening at the moment.

If we want to make it safer to include these, we should simply change to use `stdint.h`-definitions, I think.

File: src/pimp_mixer_arm.S (hunk 4 above)
Comment (kusma) [reply src/pimp_mixer_arm.S]: Ah, `pimp_config.h` is probably the proper place for this. My bad.

File: src/pimp_mixer_arm.S (hunk 9 above)
Comment (kusma) [reply src/pimp_mixer_arm.S:223]: I mean just apply this part of the code as-is. Moving the stack-pointer saving until after that return is probably the better solution, but I get rather dizzy reading this code ;)

**Comment by kusma** [comment]
Right. Yeah, so I guess that's a question of definition. I kinda left things easy to override, and I think most of this is fair. Injecting libgba cflags is totally fine; it doesn't take away the non-libgba support from other people. But LTO, I suspect is a bit much.

We could also pass `-fno-lto` at the end to disable it again. Not sure if that's better or not.

File: src/pimp_mixer.c (hunk 2 above)
Comment (PoroCYon) [reply src/pimp_mixer.c]: Alright, I'll roll it back.

File: src/pimp_base.h (hunk 1 above)
Comment (PoroCYon) [reply src/pimp_base.h]: That'd probably be a better idea in the long run, but I'll roll it back for now.

**Comment by PoroCYon** [comment]
Applied the requested changes. I'm not adding `-fno-lto` for now, though.

**Review by kusma — APPROVED** [review]
Looks great to me!

**Comment by kusma** [comment]
Thanks a lot!
